development:
  adapter: mysql
  database: openathon
  username: root
  password: Carrie0ak

production:
  adapter: mysql
  database: openathon
  username: root
  password: Carrie0ak

test:
  adapter: mysql
  database: openathon
  username: root
  password: Carrie0ak
